# Generated by Django 4.0.6 on 2022-12-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изоброжение профиля')),
                ('first_name', models.CharField(max_length=124, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=124, verbose_name='Фамилия')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('gestation_date', models.DateField(verbose_name='Дата беременности')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('city', models.CharField(max_length=124, verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=254, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.mother', verbose_name='Автор')),
            ],
        ),
    ]
