# Generated by Django 4.0.6 on 2022-12-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_mother_age_mother_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(to='src.mother', verbose_name='Автор'),
        ),
    ]
