# Generated by Django 4.0.6 on 2022-12-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_remove_post_author_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
